[package]
name = "helix_gradient_method"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peroxide = "0.37.9"
gnuplot = "0.0.43"
